branch-defaults:
  default:
    environment: staging-backend-deploy
global:
  application_name: backend-deploy
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  sc: git
  workspace_type: Application
